----- This is an automatically generated class by FairyGUI. Please do not modify it. ---
----[[
--@Description: Login.GameAgeView 工具生成的.匹配标签(窗口).自行copy字符串到文件中去
--@Author:
--@Date: Created in
----]]
----[[
--local EventManager = require('Event.EventManager')
--local EventName = require("Core.EventName")
--function GameAgeView:AddBindGlobalEvent()
--   return{
--     {GameEvent.Test,function()end,999},
--    }
--end
----]]
--local UIView = require('UI.UIView')
--local GameAgeView = fgui.window_class(UIView)
--function GameAgeView:OnLoadFinished()
----    --self.uiComs = require('UI.Packages.Login.UI_GameAgeView'):OnConstruct(self.contentPane)--self.uiComs在UIWindow.lua已有定义
----   --元素事件上,匹配元素名字 *Btn,*Ctrl,*List
--end
--
--
--function GameAgeView:SetData(pDto)
--end
--
--function GameAgeView:OnShown()
--    UIView.OnShown(self)
--end
--function GameAgeView:OnHide()
--    UIView.OnHide(self)
--end
--return GameAgeView
--
--	GameAgeView = {
--        className = 'UI.Login.GameAgeView',
--        packageName = 'Login',
--		viewName = 'GameAgeView',
--        matchMode = 0,
--        sortingOrder = 10,
--   },
--
--function ProxyLoginModule:OpenGameAgeViewData(data)
--    UIManager.OpenWindow(UIConfig.GameAgeView, function(code, view)
--        view:SetData(data)
--    end)
--end
--function ProxyLoginModule:CloseGameAgeView()
--    UIManager.CloseWindow(UIConfig.GameAgeView, true)
--end
