---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/16 22:57
---

local UIWindow = require('Core.UIWindow')
local LoginMainView = fgui.window_class(UIWindow)

function LoginMainView:LoadComponent()
    --self.uiComs = require('ToolGen.login.UI_LoginMainView'):OnConstruct(self.contentPane)
    loggZSXError("进来---------------LoginMainView")

    self.uiComs.m_loginBtn.onClick:Add(function()
        require("UI.MainCenter.ProxyMainCenterModule"):OpenMainCenter()
        self:CloseWindow()
    end)
    self:Show()
end

function LoginMainView:SetData(str)
    loggZSXError(str)
end

function LoginMainView:OnHide()
    UIWindow.OnHide(self)
end

function LoginMainView:OnShown()
    UIWindow.OnShown(self)
end

function LoginMainView:Show()
    self.visible = true
    self.contentPane.visible = true
end

return LoginMainView
