----- This is an automatically generated class by FairyGUI. Please do not modify it. ---
----[[
--@Description: Login.ServerListRemoteView 工具生成的.匹配标签(窗口).自行copy字符串到文件中去
--@Author:
--@Date: Created in
----]]
----[[
--local EventManager = require('Event.EventManager')
--local EventName = require("Core.EventName")
--function ServerListRemoteView:AddBindGlobalEvent()
--   return{
--     {GameEvent.Test,function()end,999},
--    }
--end
----]]
--local UIView = require('UI.UIView')
--local ServerListRemoteView = fgui.window_class(UIView)
--function ServerListRemoteView:OnLoadFinished()
----    --self.uiComs = require('UI.Packages.Login.UI_ServerListRemoteView'):OnConstruct(self.contentPane)--self.uiComs在UIWindow.lua已有定义
----   --元素事件上,匹配元素名字 *Btn,*Ctrl,*List
--end
--
--
--function ServerListRemoteView:SetData(pDto)
--end
--
--function ServerListRemoteView:OnShown()
--    UIView.OnShown(self)
--end
--function ServerListRemoteView:OnHide()
--    UIView.OnHide(self)
--end
--return ServerListRemoteView
--
--	ServerListRemoteView = {
--        className = 'UI.Login.ServerListRemoteView',
--        packageName = 'Login',
--		viewName = 'ServerListRemoteView',
--        matchMode = 0,
--        sortingOrder = 10,
--   },
--
--function ProxyLoginModule:OpenServerListRemoteViewData(data)
--    UIManager.OpenWindow(UIConfig.ServerListRemoteView, function(code, view)
--        view:SetData(data)
--    end)
--end
--function ProxyLoginModule:CloseServerListRemoteView()
--    UIManager.CloseWindow(UIConfig.ServerListRemoteView, true)
--end
