local GMConfig = {
    [1]={id=1,tType=1,tTypeName="角色（英雄）",tContent="获取英雄（只能已配置的）",tGmTxt="HeroGm addHero 1",tDesc="HeroGm addHero [英雄id]",},
    [2]={id=2,tType=1,tTypeName="角色（英雄）",tContent="增加英雄经验",tGmTxt="HeroGm addHeroExp 1:800",tDesc="HeroGm addHeroExp [英雄id:增加的经验]",},
    [3]={id=3,tType=1,tTypeName="角色（英雄）",tContent="英雄升阶",tGmTxt="HeroGm upStair 1",tDesc="HeroGm upStair [英雄id]",},
    [4]={id=4,tType=1,tTypeName="角色（英雄）",tContent="英雄升星",tGmTxt="HeroGm upStar 1",tDesc="HeroGm upStar [英雄id]",},
    [5]={id=5,tType=1,tTypeName="角色（英雄）",tContent="拥有【数量】个英雄",tGmTxt="HeroGm prepareHeroList 20",tDesc="HeroGm prepareHeroList [个数]",},
    [6]={id=6,tType=1,tTypeName="角色（英雄）",tContent="获得因缘经验(重登生效)",tGmTxt="HeroGm addManualExp 100",tDesc="HeroGm addManualExp [因缘经验]",},
    [7]={id=7,tType=2,tTypeName="技能",tContent="技能升级",tGmTxt="HeroGm skillUpgrade 1:2",tDesc="HeroGm skillUpgrade[英雄id:英雄等级]",},
    [9]={id=9,tType=3,tTypeName="配料系统",tContent="获得配料",tGmTxt="IngredientGm addIngredient 1061001",tDesc="IngredientGm addIngredient [配料的物品配置id]",},
    [10]={id=10,tType=3,tTypeName="配料系统",tContent="升级配料",tGmTxt="IngredientGm upGradeIngredient 3237245537453736010",tDesc="IngredientGm upGradeIngredient [配料唯一id]",},
    [11]={id=11,tType=4,tTypeName="宝物系统",tContent="获得宝物",tGmTxt="TreasureGm getTreasure 1,2,3,4",tDesc="TreasureGm getTreasure [宝物id,宝物id]（逗号隔开）",},
    [12]={id=12,tType=4,tTypeName="宝物系统",tContent="宝物升级",tGmTxt="TreasureGm treasureUpgrade 1",tDesc="TreasureGm treasureUpgrade [宝物id]",},
    [13]={id=13,tType=5,tTypeName="任务系统",tContent="完成指定任务",tGmTxt="TaskGm finishTask 401002",tDesc="TaskGm finishTask [任务id]",},
    [14]={id=14,tType=5,tTypeName="任务系统",tContent="领取指定任务",tGmTxt="TaskGm receiveTask 401002",tDesc="TaskGm receiveTask [任务id]",},
    [15]={id=15,tType=5,tTypeName="任务系统",tContent="完成指定进度",tGmTxt="TaskGm finishProgress 14002:5_3",tDesc="TaskGm finishProgress [条件id:参数1_参数2_参数3..]（最多四个参数）",},
    [16]={id=16,tType=5,tTypeName="任务系统",tContent="领取该类型所有已完成的任务",tGmTxt="TaskGm pickAllFinishTask 11",tDesc="TaskGm pickAllFinishTask [任务类型]",},
    [17]={id=17,tType=5,tTypeName="任务系统",tContent="完成当前等级全部城堡任务",tGmTxt="TaskGm finishCastleTask",tDesc="CastleGm finishCastleTask",},
    [18]={id=18,tType=6,tTypeName="公会",tContent="重置每日挑战次数",tGmTxt="GuildGm resetCrusadeTime",tDesc="GuildGm resetCrusadeTime",},
    [19]={id=19,tType=6,tTypeName="公会",tContent="设置讨伐阶段",tGmTxt="GuildGm setCrusadeStage 2",tDesc="GuildGm setCrusadeStage [阶段id]",},
    [20]={id=20,tType=6,tTypeName="公会",tContent="重置每日捐赠次数",tGmTxt="GuildGm resetDonationNum",tDesc="GuildGm resetDonationNum",},
    [21]={id=21,tType=6,tTypeName="公会",tContent="设置公会讨伐奖杯",tGmTxt="GuildGm addGuildCup 100",tDesc="GuildGm addGuildCup [奖杯数量]",},
    [22]={id=22,tType=6,tTypeName="公会",tContent="增加公会经验",tGmTxt="GuildGm addGuildExp 100",tDesc="GuildGm addGuildExp [经验值]",},
    [23]={id=23,tType=6,tTypeName="公会",tContent="公会升级",tGmTxt="GuildGm guildUpGrade",tDesc="GuildGm guildUpGrade",},
    [24]={id=24,tType=6,tTypeName="公会",tContent="增加公会道具",tGmTxt="GuildGm addGuildItem 1014001:100",tDesc="GuildGm addGuildItem [道具id:数量]",},
    [25]={id=25,tType=6,tTypeName="公会",tContent="增加公会活跃度",tGmTxt="GuildGm addActivity 100",tDesc="GuildGm addActivity [活跃度]",},
    [26]={id=26,tType=7,tTypeName="成就",tContent="完成所有成就（需要重登，使用后会卡2、3分钟）",tGmTxt="AchievementGm finishAll",tDesc="AchievementGm finishAll",},
    [27]={id=27,tType=7,tTypeName="成就",},
    [28]={id=28,tType=8,tTypeName="场景和建筑",tContent="购买和放置建筑",tGmTxt="SceneGm buildingBuy 10001 10 20",tDesc="SceneGm buildingBuy buidingId x y",},
    [29]={id=29,tType=8,tTypeName="场景和建筑",tContent="加速建筑创建和升级",tGmTxt="SceneGm buildingSpeedUpUpgrade 5 3000",tDesc="SceneGm buildingSpeedUpUpgrade SceneIndex time （时间：秒）",},
    [30]={id=30,tType=8,tTypeName="场景和建筑",tContent="加速建筑生产",tGmTxt="SceneGm buildingSpeedUpProduction 5 3000",tDesc="SceneGm buildingSpeedUpProduction buidingId time （时间：秒）",},
    [31]={id=31,tType=8,tTypeName="场景和建筑",tContent="加速杂物清除",tGmTxt="SceneGm sundriesSpeedUp 5 3000",tDesc="SceneGm sundriesSpeedUp index time （时间：秒）",},
    [32]={id=32,tType=8,tTypeName="场景和建筑",tContent="加速区域解锁",tGmTxt="SceneGm blockSpeedUp 5 3000",tDesc="SceneGm blockSpeedUp blockId time （时间：秒）",},
    [33]={id=33,tType=8,tTypeName="场景和建筑",tContent="清除非固定位置所有建筑",tGmTxt="SceneGm clearBuildings",tDesc="SceneGm clearBuildings （无参数）",},
    [34]={id=34,tType=8,tTypeName="场景和建筑",tContent="开发所有区域",tGmTxt="SceneGm openAllBlocks",tDesc="SceneGm openAllBlocks（无参数）",},
    [35]={id=35,tType=8,tTypeName="场景和建筑",tContent="场景中建筑升到某个等级",tGmTxt="SceneGm buildingUpgrade 10001 10",tDesc="SceneGm buildingUpgrade buildingId level",},
    [36]={id=36,tType=8,tTypeName="场景和建筑",tContent="场景中（非固定）建筑升到满级",tGmTxt="SceneGm upgradeMax",tDesc="SceneGm upgradeMax（无参数）",},
    [37]={id=37,tType=9,tTypeName="热带苏打群岛",tContent="解锁迷雾",tGmTxt="SodaIslandGm open 1",tDesc="SodaIslandGm open [群岛建筑ID]",},
    [38]={id=38,tType=9,tTypeName="热带苏打群岛",tContent="占领资源群岛",tGmTxt="SodaIslandGm occupy 1",tDesc="SodaIslandGm occupy [群岛建筑ID]",},
    [39]={id=39,tType=9,tTypeName="热带苏打群岛",tContent="更新第一次占领时间",tGmTxt="SodaIslandGm firstTime 1",tDesc="SodaIslandGm firstTime [相对现在提前的小时数量]",},
    [40]={id=40,tType=9,tTypeName="热带苏打群岛",tContent="更新占领时间",tGmTxt="SodaIslandGm occupiedTime 1 1",tDesc="SodaIslandGm occupiedTime [建筑ID] [相对现在提前的小时数量]",},
    [41]={id=41,tType=9,tTypeName="热带苏打群岛",tContent="更新结算奖励的参考时间",tGmTxt="SodaIslandGm settledTime 1",tDesc="SodaIslandGm settledTime [相对现在提前的小时数量]",},
    [42]={id=42,tType=9,tTypeName="热带苏打群岛",tContent="设置可回收的资源岛屿数量",tGmTxt="SodaIslandGm recycle 2",tDesc="SodaIslandGm recycle [可回收数量]",},
    [43]={id=43,tType=10,tTypeName="货币",tContent="增加金币",tGmTxt="BagGm addItem 1011001:100000",tDesc="使用背包gm addItem",},
    [44]={id=44,tType=10,tTypeName="货币",tContent="增加钻石",tGmTxt="BagGm addItem 1011002:100000",tDesc="使用背包gm addItem",},
    [45]={id=45,tType=10,tTypeName="货币",tContent="减少货币",tGmTxt="BagGm reduceItem 1011001:1",tDesc="使用背包gm reduceItem",},
    [46]={id=46,tType=11,tTypeName="王国资讯",tContent="设置王国等级",tGmTxt="KingdomGm setLevel 20",tDesc="KingdomGm setLevel [王国等级]",},
    [47]={id=47,tType=11,tTypeName="王国资讯",tContent="解锁头像",tGmTxt="KingdomGm unlockHead 1 1",tDesc="KingdomGm unlockHead [解锁类型] [解锁条件]",},
    [48]={id=48,tType=12,tTypeName="世界探险",tContent="通过关卡",tGmTxt="AdventureGm setCheckId 1001 10102",tDesc="AdventureGm setCheckId [区域id] [关卡id]",},
    [49]={id=49,tType=12,tTypeName="世界探险",tContent="重置暗黑所有关卡挑战次数",tGmTxt="AdventureGm resetTime",tDesc="AdventureGm resetTime",},
    [50]={id=50,tType=12,tTypeName="世界探险",tContent="重置城镇互动数据",tGmTxt="AdventureGm clearTownInfo 1001 2001",tDesc="AdventureGm clearTownInfo 区域id 城镇id",},
    [51]={id=51,tType=12,tTypeName="世界探险",},
    [52]={id=52,tType=13,tTypeName="仓库系统",tContent="添加资源（除货币外，其他道具每次最多只能添加999个）",tGmTxt="BagGm addItem 1031001:11",tDesc="BagGm addItem [道具ID:数量] 多个道具用分号隔开",},
    [53]={id=53,tType=13,tTypeName="仓库系统",tContent="消耗资源",tGmTxt="BagGm reduceItem 1031001:11",tDesc="BagGm reduceItem [道具ID:数量] 多个道具用分号隔开",},
    [54]={id=54,tType=13,tTypeName="仓库系统",tContent="清空背包gm",tGmTxt="BagGm clearBag",tDesc="BagGm clearBag",},
    [55]={id=55,tType=13,tTypeName="仓库系统",},
    [56]={id=56,tType=14,tTypeName="剧情",tContent="完成剧情对话",tGmTxt="DialogueGm finish 1",tDesc="DialogueGm finish [剧情ID]",},
    [57]={id=57,tType=14,tTypeName="剧情",tContent="播放剧情对话",tGmTxt="local playDialogue 5",tDesc="local playDialogue [剧情ID]",},
    [58]={id=58,tType=15,tTypeName="许愿树，列车",tContent="重置每日奖励",tGmTxt="FreightGm resetDayReward 17",tDesc="FreightGm resetDayReward [功能ID]",},
    [59]={id=59,tType=15,tTypeName="许愿树，列车",tContent="任务重新整理",tGmTxt="FreightGm refresh 17 0",tDesc="FreightGm refresh [功能ID] [任务槽位]（四个任务的槽位分别是0,1,2,3）",},
    [60]={id=60,tType=15,tTypeName="许愿树，列车",tContent="修改许愿树每日奖励领取次数",tGmTxt="FreightGm setDayRewardNum 1",tDesc="FreightGm setDayRewardNum [领取次数]",},
    [61]={id=61,tType=15,tTypeName="许愿树，列车",tContent="添加许愿树或列车完成次数",tGmTxt="FreightGm setPassNum 17 15",tDesc="FreightGm setPassNum [功能ID] [添加次数]",},
    [62]={id=62,tType=15,tTypeName="许愿树，列车",tContent="交付任务",tGmTxt="FreightGm submit 109",tDesc="FreightGm submit 109 一次性装满列车货物，针对列车系统",},
    [63]={id=63,tType=16,tTypeName="地精研究室",},
    [64]={id=64,tType=16,tTypeName="地精研究室",tContent="设置研究等级(要先满足研究所等级)",tGmTxt="GoblinGm setGoblinLab 1 2",tDesc="GoblinGm setGoblinLab [研究id] [研究等级]",},
    [65]={id=65,tType=16,tTypeName="地精研究室",tContent="解锁或研究加速",tGmTxt="GoblinGm speed 2 0 1023001:1",tDesc="GoblinGm speed 2 [是否立刻完成] [加速道具]",},
    [66]={id=66,tType=16,tTypeName="地精研究室",},
    [67]={id=67,tType=17,tTypeName="喷水池",},
    [68]={id=68,tType=17,tTypeName="喷水池",tContent="获得当前等级的满奖励",tGmTxt="FountainGm fullReward",tDesc="FountainGm fullReward",},
    [69]={id=69,tType=17,tTypeName="喷水池",},
    [70]={id=70,tType=18,tTypeName="邮箱",tContent="发送邮件",tGmTxt="MailGm sendMail 1 101 1011001:1 1",tDesc="MailGm sendMail 邮件类型 邮件内容id 奖励 参数，没有就不填，多个用逗号隔开 （自己给自己发的GM）",},
    [71]={id=71,tType=18,tTypeName="邮箱",tContent="隔天清理邮件",tGmTxt="MailGm dayCheck",tDesc="MailGm dayCheck",},
    [72]={id=72,tType=18,tTypeName="邮箱",},
    [73]={id=73,tType=19,tTypeName="竞技场",},
    [74]={id=74,tType=19,tTypeName="竞技场",tContent="战斗准备",tGmTxt="ArenaGm fightPrepare 1 1 0",tDesc="ArenaGm fightPrepare [战斗类型：1对战，2复仇] [pvp对战列表key值/复仇列表索引值] [队伍索引]",},
    [75]={id=75,tType=19,tTypeName="竞技场",tContent="战斗结果上传",tGmTxt="ArenaGm fightend 1",tDesc="ArenaGm fightend [战斗结果：1胜利(复仇成功)，2失败（复仇失败），3平手（复仇平手）]",},
    [76]={id=76,tType=19,tTypeName="竞技场",tContent="模拟解锁",tGmTxt="ArenaGm gmUnlock 1",tDesc="ArenaGm gmUnlock 1（添加1-5英雄并设置为防守队伍）",},
    [77]={id=77,tType=19,tTypeName="竞技场",tContent="刷新对手",tGmTxt="ArenaGm refreshFight 0",tDesc="ArenaGm refreshFight 0 刷新对手",},
    [78]={id=78,tType=19,tTypeName="竞技场",tContent="刷新内置总排行榜",tGmTxt="ArenaGm calcTotalPowerRank 0",tDesc="ArenaGm calcTotalPowerRank 0 刷新内置总排行榜",},
    [79]={id=79,tType=19,tTypeName="竞技场",tContent="设置奖杯数",tGmTxt="ArenaGm setTrophy 100",tDesc="ArenaGm setTrophy [奖杯数]",},
    [80]={id=80,tType=20,tTypeName="充值",tContent="充值",tGmTxt="RechargeGm buy 1",tDesc="RechargeGm buy [productId] 充值表中的产品Id",},
    [81]={id=81,tType=20,tTypeName="充值",},
    [82]={id=82,tType=21,tTypeName="蛋糕塔",tContent="解锁前N层关卡",tGmTxt="CakeTowerGm setLayer 10",tDesc="CakeTowerGm setLayer [层数]",},
    [83]={id=83,tType=21,tTypeName="蛋糕塔",},
    [84]={id=84,tType=22,tTypeName="服装",tContent="获得服装",tGmTxt="SuitGm getSuit 1",tDesc="SuitGm getSuit [服装id]",},
    [85]={id=85,tType=22,tTypeName="服装",tContent="套用服装",tGmTxt="SuitGm wearSuit 1",tDesc="SuitGm wearSuit [服装id]",},
    [86]={id=86,tType=22,tTypeName="服装",tContent="获取所有服装因缘",tGmTxt="SuitGm setActivate",},
    [87]={id=87,tType=23,tTypeName="大贸易时代",tContent="添加贸易点数",tGmTxt="TradeEpochGm addPoint 23456",tDesc="TradeEpochGm addPoint [添加的点数]",},
    [88]={id=88,tType=23,tTypeName="大贸易时代",},
    [89]={id=89,tType=24,tTypeName="大乱斗",tContent="设置大乱斗奖杯数",tGmTxt="ChaosGm setTrophy 1000",tDesc="ChaosGm setTrophy [奖杯数]",},
    [90]={id=90,tType=24,tTypeName="大乱斗",},
    [91]={id=91,tType=25,tTypeName="公会研究室",tContent="立刻完成当前研究",tGmTxt="GuildLabGm finish",tDesc="GuildLabGm finish",},
    [92]={id=92,tType=25,tTypeName="公会研究室",tContent="设置研究等级(要先满足公会等级)",tGmTxt="GuildLabGm setGuildLab 111 2",tDesc="GuildLabGm setGuildLab [研究id] [研究等级]",},
    [93]={id=93,tType=26,tTypeName="新手引导",tContent="跳过所有新手引导",tGmTxt="GuideGm skipAll",tDesc="GuideGm skipAll",},
    [94]={id=94,tType=26,tTypeName="新手引导",tContent="已触发引导后仍跳过所有新手引导",tGmTxt="local guideQuit",tDesc="local guideQuit",},
    [95]={id=95,tType=26,tTypeName="新手引导",tContent="本次跳过引导，后续满足条件还是可以触发引导",tGmTxt="local guideSkip",tDesc="local guideSkip",},
    [96]={id=96,tType=26,tTypeName="新手引导",tContent="直接运行指定的引导步骤，并根据操作进行下面的引导行为",tGmTxt="local guideRun 3 2",tDesc="local guideRun [引导id] [步骤id]",},
    [97]={id=97,tType=26,tTypeName="新手引导",tContent="检测舞台点击.Log",tGmTxt="local guideNeedPath 1",tDesc="1开  0关",},
    [98]={id=98,tType=27,tTypeName="功能开启",tContent="开放所有系统（会导致某些任务进度出问题）",tGmTxt="FuncGm unlockAll",tDesc="FuncGm unlockAll",},
    [99]={id=99,tType=27,tTypeName="功能开启",},
    [100]={id=100,tType=28,tTypeName="航海商人",tContent="快速完成所有运输订单",tGmTxt="VoyageGm speed",},
    [101]={id=101,tType=28,tTypeName="航海商人",tContent="刷新对手",tGmTxt="VoyageGm refreshRival",},
    [102]={id=102,tType=28,tTypeName="航海商人",tContent="快速获取普通商人货物",tGmTxt="VoyageGm getItems",},
    [103]={id=103,tType=28,tTypeName="航海商人",tContent="掠夺刷新重置",tGmTxt="VoyageGm reset",},
    [104]={id=104,tType=28,tTypeName="航海商人",tContent="跳过航海新手引导",tGmTxt="VoyageGm skipGuide",tDesc="功能开启前使用",},
    [105]={id=105,tType=28,tTypeName="航海商人",tContent="重置求助次数",tGmTxt="VoyageGm resetHelp",},
    [106]={id=106,tType=29,tTypeName="生产工坊（餐厅）",tContent="重置所有订单信息",tGmTxt="WorkShopGm resetData",},
    [107]={id=107,tType=29,tContent="增加好感度值",tGmTxt="WorkShopGm addFavoriteCount 100",tDesc="WorkShopGm addFavoriteCount [增加的点赞数]",},
    [108]={id=108,tType=29,tContent="重置新手引导订单",tGmTxt="WorkShopGm refreshGuide",},
    [109]={id=109,tType=29,tContent="刷新特殊订单",tGmTxt="WorkShopGm specialOrder 2",tDesc="WorkShopGm specialOrder [特殊订单类型]",},
    [110]={id=110,tType=30,tTypeName="装备商人",tContent="增加积分",tGmTxt="EquipMerchantGm addPoint 1 200",tDesc="EquipMerchantGm addPoint[商店等级][积分]",},
    [111]={id=111,tType=31,tTypeName="精灵圣树",tContent="获取灵气",tGmTxt="HolyTreeGm full",tDesc="达到圣树等级可获取的最大灵气值",},
    [112]={id=112,tType=32,tTypeName="驿站",tContent="随机刷新一个事件",tGmTxt="StageGm generate",tDesc="StageGm generate",},
    [113]={id=113,tType=32,tTypeName="驿站",tContent="刷新指定事件",tGmTxt="StageGm refreshEvent 10001",tDesc="StageGm refreshEvent 事件id",},
    [114]={id=114,tType=32,tTypeName="驿站",tContent="清空所有事件数据",tGmTxt="StageGm clear",tDesc="StageGm clear",},
    [115]={id=115,tType=32,tTypeName="驿站",tContent="重置加速次数",tGmTxt="StageGm clearQuick",},
    [116]={id=116,tType=33,tTypeName="其他",tContent="播放UI特效",tGmTxt="local playUIEffectId 1002",tDesc="1002是特效表的id",},
    [117]={id=117,tType=33,tTypeName="其他",tContent="换算出城堡升级辐射特效值",tGmTxt="local TestCatleTxCameraPos 12 -43 69",tDesc="12为镜头高度，[-43,69]为镜头位置，使用后得出xy填表",},
    [118]={id=118,tType=33,tTypeName="其他",tContent="城堡升级辐射特效测试",tGmTxt="local TestCatleTxCamera 1",tDesc="1为城堡等级",},
    [119]={id=119,tType=33,tTypeName="其他",tContent="测试公告跳转方式",tGmTxt="local funcGoTo Shop_1",tDesc="Shop_1[shop为功能开启名，_1为礼包类型id]",},
};

local DefaultValueTable = {
    id=0,tType=0,tTypeName="",tContent="",tGmTxt="",tDesc="",
};

local base = { __index = DefaultValueTable }
for _,v in pairs(GMConfig) do
    setmetatable(v, base)

end

return GMConfig
