---@class System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event : LuaInterface.LuaDelegate
System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event = {}

---@param func : LuaInterface.LuaFunction
---@return System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event
function System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event(func)
end

---@param func : LuaInterface.LuaFunction
---@param self : LuaInterface.LuaTable
---@return System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event
function System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event(func, self)
end

---@param param0 : UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle
function System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event:Call(param0)
end

---@param param0 : UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle
function System_Action_UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object_Event:CallWithSelf(param0)
end