--- This is an automatically generated class by FairyGUI. Please do not modify it. ---
---@class UI_ResourceTipsView : CS.FairyGUI.GLabel
local UI_ResourceTipsView = {};
function UI_ResourceTipsView:OnConstruct(windowCom)
	local tb = {
	m_state = windowCom:GetController("state"),
	m_tips = windowCom:GetController("tips"),
	m_belong = windowCom:GetController("belong"),
	m_arrow = windowCom:GetChild("arrow"),
	m_n2 = windowCom:GetChild("n2"),
	m_resLandName = windowCom:GetChild("resLandName"),
	m_shareBtn = windowCom:GetChild("shareBtn"),
	m_collectionBtn = windowCom:GetChild("collectionBtn"),
	m_n9 = windowCom:GetChild("n9"),
	m_attack = windowCom:GetChild("attack"),
	m_inforTitle0 = windowCom:GetChild("inforTitle0"),
	m_inforTime = windowCom:GetChild("inforTime"),
	m_leagueName = windowCom:GetChild("leagueName"),
	m_typeIcon = windowCom:GetChild("typeIcon"),
	m_monsterTitle = windowCom:GetChild("monsterTitle"),
	m_n87 = windowCom:GetChild("n87"),
	m_monsterPower = windowCom:GetChild("monsterPower"),
	m_recommend = windowCom:GetChild("recommend"),
	m_efficiencyTitle = windowCom:GetChild("efficiencyTitle"),
	m_efficient = windowCom:GetChild("efficient"),
	m_state02 = windowCom:GetChild("state02"),
	m_heroTitle = windowCom:GetChild("heroTitle"),
	m_heroList = windowCom:GetChild("heroList"),
	m_inforTitle2 = windowCom:GetChild("inforTitle2"),
	m_gatherList = windowCom:GetChild("gatherList"),
	m_state13 = windowCom:GetChild("state13"),
	m_tips0 = windowCom:GetChild("tips0"),
	m_tipsLbl = windowCom:GetChild("tipsLbl"),
	m_explainBtn = windowCom:GetChild("explainBtn"),
	m_explainBtn2 = windowCom:GetChild("explainBtn2"),
	m_attackBtn = windowCom:GetChild("attackBtn"),
	m_gatherBtn = windowCom:GetChild("gatherBtn"),
	m_fightBtn = windowCom:GetChild("fightBtn"),
	m_backBtn = windowCom:GetChild("backBtn"),
	m_monsterIcon = windowCom:GetChild("monsterIcon"),
	m_bossIcon = windowCom:GetChild("bossIcon"),
	m_roleHead = windowCom:GetChild("roleHead"),
	m_leagueFlag = windowCom:GetChild("leagueFlag"),
	m_n78 = windowCom:GetChild("n78"),
	m_coordTitle = windowCom:GetChild("coordTitle"),
	m_n77 = windowCom:GetChild("n77"),
	}
	return tb
end
return UI_ResourceTipsView;