--- This is an automatically generated class by FairyGUI. Please do not modify it. ---
---@class UI_DialogWorldBossView : CS.FairyGUI.GLabel
local UI_DialogWorldBossView = {};
function UI_DialogWorldBossView:OnConstruct(windowCom)
	local tb = {
	m_tipCtrl = windowCom:GetController("tipCtrl"),
	m_btnCountCtrl = windowCom:GetController("btnCountCtrl"),
	m_mask = windowCom:GetChild("mask"),
	m_showTopTitle = windowCom:GetChild("showTopTitle"),
	m_window = windowCom:GetChild("window"),
	m_EffectHandle_GongXiHuoDe = windowCom:GetChild("EffectHandle_GongXiHuoDe"),
	m_txtDesc = windowCom:GetChild("txtDesc"),
	m_n60 = windowCom:GetChild("n60"),
	m_n93 = windowCom:GetChild("n93"),
	m_n95 = windowCom:GetChild("n95"),
	m_n96 = windowCom:GetChild("n96"),
	m_ranking_list = windowCom:GetChild("ranking_list"),
	m_rankinglbl = windowCom:GetChild("rankinglbl"),
	m_hurtLbl = windowCom:GetChild("hurtLbl"),
	m_minebg = windowCom:GetChild("minebg"),
	m_rankmine = windowCom:GetChild("rankmine"),
	m_friendhelp = windowCom:GetChild("friendhelp"),
	m_details = windowCom:GetChild("details"),
	m_awardbg = windowCom:GetChild("awardbg"),
	m_rewardlbl = windowCom:GetChild("rewardlbl"),
	m_reward_list = windowCom:GetChild("reward_list"),
	m_rewardlbl01 = windowCom:GetChild("rewardlbl01"),
	m_rewardlbl02 = windowCom:GetChild("rewardlbl02"),
	m_rewardlbl03 = windowCom:GetChild("rewardlbl03"),
	m_timeTip = windowCom:GetChild("timeTip"),
	m_n68 = windowCom:GetChild("n68"),
	m_tipsdet = windowCom:GetChild("tipsdet"),
	m_n101 = windowCom:GetChild("n101"),
	m_com = windowCom:GetChild("com"),
	m_panel = windowCom:GetChild("panel"),
	m_confirmBtn = windowCom:GetChild("confirmBtn"),
	m_quitBtn = windowCom:GetChild("quitBtn"),
	m_confirmBtn01 = windowCom:GetChild("confirmBtn01"),
	m_btn = windowCom:GetChild("btn"),
	m_n99 = windowCom:GetChild("n99"),
	m_mask1 = windowCom:GetChild("mask1"),
	m_n91 = windowCom:GetChild("n91"),
	m_rank_list = windowCom:GetChild("rank_list"),
	m_n78 = windowCom:GetChild("n78"),
	m_detailTip = windowCom:GetChild("detailTip"),
	m_t0 = windowCom:GetTransition("t0"),
	}
	return tb
end
return UI_DialogWorldBossView;