--- This is an automatically generated class by FairyGUI. Please do not modify it. ---

---@class UI_main_subjectNew : CS.FairyGUI.GComponent
--字段省略
local UI_main_subjectNew = {};
--UI_main_subjectNew.URL = "ui://main/main_subjectNew";
function UI_main_subjectNew:OnConstruct(windowCom)
	local tb = {
	m_rightTeam = windowCom:GetController("rightTeam"),
	m_map = windowCom:GetController("map"),
	m_view = windowCom:GetController("view"),
	m_inOrOut = windowCom:GetController("inOrOut"),
	m_coordinate = windowCom:GetController("coordinate"),
	m_n145 = windowCom:GetChild("n145"),
	m_task = windowCom:GetChild("task"),
	m_task_main_treasure = windowCom:GetChild("task_main_treasure"),
	m_worldLeaders = windowCom:GetChild("worldLeaders"),
	m_leagueLeaders = windowCom:GetChild("leagueLeaders"),
	m_chief = windowCom:GetChild("chief"),
	m_main_mapMini01 = windowCom:GetChild("main_mapMini01"),
	m_miniMap = windowCom:GetChild("miniMap"),
	m_activityList = windowCom:GetChild("activityList"),
	m_warningBtn = windowCom:GetChild("warningBtn"),
	m_city_out = windowCom:GetChild("city_out"),
	m_city_in = windowCom:GetChild("city_in"),
	m_limitBtnList = windowCom:GetChild("limitBtnList"),
	m_teamWalking = windowCom:GetChild("teamWalking"),
	m_mainView = windowCom:GetChild("mainView"),
	m_defendCityBattleView = windowCom:GetChild("defendCityBattleView"),
	m_n55 = windowCom:GetChild("n55"),
	m_chatBtn = windowCom:GetChild("chatBtn"),
	m_red = windowCom:GetChild("red"),
	m_chatPart = windowCom:GetChild("chatPart"),
	m_backBtn = windowCom:GetChild("backBtn"),
	m_outBtn = windowCom:GetChild("outBtn"),
	m_underRight_btn = windowCom:GetChild("underRight_btn"),
	m_team = windowCom:GetChild("team"),
	m_worldBossHp = windowCom:GetChild("worldBossHp"),
	m_leaBossHp = windowCom:GetChild("leaBossHp"),
	m_singleBossHp = windowCom:GetChild("singleBossHp"),
	m_coordCloseBtn = windowCom:GetChild("coordCloseBtn"),
	m_playerIcon = windowCom:GetChild("playerIcon"),
	m_coordItemItem = windowCom:GetChild("coordItemItem"),
	m_propTopList = windowCom:GetChild("propTopList"),
	m_coordItemBtn = windowCom:GetChild("coordItemBtn"),
	m_collectionBtn = windowCom:GetChild("collectionBtn"),
	m_weather = windowCom:GetChild("weather"),
	m_topLeft = windowCom:GetChild("topLeft"),
	m_searchView = windowCom:GetChild("searchView"),
	m_search = windowCom:GetChild("search"),
	m_noviceBossBattleView = windowCom:GetChild("noviceBossBattleView"),
	m_plotBattleView = windowCom:GetChild("plotBattleView"),
	m_fightReportBtn = windowCom:GetChild("fightReportBtn"),
	m_area_mini = windowCom:GetChild("area_mini"),
	m_area_out = windowCom:GetChild("area_out"),
	m_area_in = windowCom:GetChild("area_in"),
	m_area_plot = windowCom:GetChild("area_plot"),
	m_exitWorldBossBtn = windowCom:GetChild("exitWorldBossBtn"),
	m_btn_switch = windowCom:GetChild("btn_switch"),
	m_switchBtnList = windowCom:GetChild("switchBtnList"),
	m_localKillCom = windowCom:GetChild("localKillCom"),
	m_n190 = windowCom:GetChild("n190"),
	m_seeText = windowCom:GetChild("seeText"),
	m_v10 = windowCom:GetChild("v10"),
	m_quit = windowCom:GetTransition("quit"),
	m_approach = windowCom:GetTransition("approach"),
	m_a_personalboss = windowCom:GetTransition("a_personalboss"),
	m_a_worldboss = windowCom:GetTransition("a_worldboss"),
	}
	return tb
end
return UI_main_subjectNew;