---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.   fgui-->mainTopPlayerInfo
--- DateTime: 2022/8/28 21:28
---

local TopEles = {}

function TopEles:Init(rootUI)
    if rootUI then
        self.uiComs = require('ToolGen.Main.UI_TopEles'):OnConstruct(rootUI.m_topEles)

        self.uiComs.m_mainPlayerBtn.onClick:Add(function()
            require("UI.MainRole.ProxyMainRoleModule"):OpenRoleMainView()
        end)
    end
end

function TopEles:Dispose()

end

return TopEles
