//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EmojiMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EmojiMgr), typeof(System.Object));
		L.RegFunction("New", _CreateEmojiMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Emojies", get_Emojies, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateEmojiMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				string arg1 = ToLua.CheckString(L, 2);
				EmojiMgr obj = new EmojiMgr(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: EmojiMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Emojies(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EmojiMgr obj = (EmojiMgr)o;
			System.Collections.Generic.Dictionary<uint,FairyGUI.Emoji> ret = obj.Emojies;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Emojies on a nil value");
		}
	}
}

