//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_OriginHorizontalWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.OriginHorizontal));
		L.RegVar("Left", get_Left, null);
		L.RegVar("Right", get_Right, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.OriginHorizontal>.Check = CheckType;
		StackTraits<FairyGUI.OriginHorizontal>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.OriginHorizontal arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.OriginHorizontal), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Left(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.OriginHorizontal.Left);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Right(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.OriginHorizontal.Right);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.OriginHorizontal o = (FairyGUI.OriginHorizontal)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

