//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_ObjectTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.ObjectType));
		L.RegVar("Image", get_Image, null);
		L.RegVar("MovieClip", get_MovieClip, null);
		L.RegVar("Swf", get_Swf, null);
		L.RegVar("Graph", get_Graph, null);
		L.RegVar("Loader", get_Loader, null);
		L.RegVar("Group", get_Group, null);
		L.RegVar("Text", get_Text, null);
		L.RegVar("RichText", get_RichText, null);
		L.RegVar("InputText", get_InputText, null);
		L.RegVar("Component", get_Component, null);
		L.RegVar("List", get_List, null);
		L.RegVar("Label", get_Label, null);
		L.RegVar("Button", get_Button, null);
		L.RegVar("ComboBox", get_ComboBox, null);
		L.RegVar("ProgressBar", get_ProgressBar, null);
		L.RegVar("Slider", get_Slider, null);
		L.RegVar("ScrollBar", get_ScrollBar, null);
		L.RegVar("Tree", get_Tree, null);
		L.RegVar("Loader3D", get_Loader3D, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.ObjectType>.Check = CheckType;
		StackTraits<FairyGUI.ObjectType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.ObjectType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.ObjectType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Image(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Image);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MovieClip(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.MovieClip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Swf(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Swf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Graph(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Graph);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loader(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Loader);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Group(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Group);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Text(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Text);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RichText(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.RichText);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InputText(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.InputText);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Component(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Component);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_List(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.List);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Label(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Label);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Button(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Button);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ComboBox(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.ComboBox);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ProgressBar(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.ProgressBar);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Slider(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Slider);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScrollBar(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.ScrollBar);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Tree(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Tree);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loader3D(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ObjectType.Loader3D);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.ObjectType o = (FairyGUI.ObjectType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

