//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_PopupDirectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.PopupDirection));
		L.RegVar("Auto", get_Auto, null);
		L.RegVar("Up", get_Up, null);
		L.RegVar("Down", get_Down, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.PopupDirection>.Check = CheckType;
		StackTraits<FairyGUI.PopupDirection>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.PopupDirection arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.PopupDirection), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Auto(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.PopupDirection.Auto);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Up(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.PopupDirection.Up);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Down(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.PopupDirection.Down);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.PopupDirection o = (FairyGUI.PopupDirection)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

