//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_FillMethodWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.FillMethod));
		L.RegVar("None", get_None, null);
		L.RegVar("Horizontal", get_Horizontal, null);
		L.RegVar("Vertical", get_Vertical, null);
		L.RegVar("Radial90", get_Radial90, null);
		L.RegVar("Radial180", get_Radial180, null);
		L.RegVar("Radial360", get_Radial360, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.FillMethod>.Check = CheckType;
		StackTraits<FairyGUI.FillMethod>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.FillMethod arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.FillMethod), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Horizontal(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.Horizontal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Vertical(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.Vertical);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Radial90(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.Radial90);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Radial180(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.Radial180);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Radial360(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillMethod.Radial360);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.FillMethod o = (FairyGUI.FillMethod)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

