//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_OriginVerticalWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.OriginVertical));
		L.RegVar("Top", get_Top, null);
		L.RegVar("Bottom", get_Bottom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.OriginVertical>.Check = CheckType;
		StackTraits<FairyGUI.OriginVertical>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.OriginVertical arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.OriginVertical), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Top(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.OriginVertical.Top);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bottom(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.OriginVertical.Bottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.OriginVertical o = (FairyGUI.OriginVertical)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

