//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_Origin90Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.Origin90));
		L.RegVar("TopLeft", get_TopLeft, null);
		L.RegVar("TopRight", get_TopRight, null);
		L.RegVar("BottomLeft", get_BottomLeft, null);
		L.RegVar("BottomRight", get_BottomRight, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.Origin90>.Check = CheckType;
		StackTraits<FairyGUI.Origin90>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.Origin90 arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.Origin90), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TopLeft(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.Origin90.TopLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TopRight(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.Origin90.TopRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BottomLeft(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.Origin90.BottomLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BottomRight(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.Origin90.BottomRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.Origin90 o = (FairyGUI.Origin90)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

