//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_ScrollBarDisplayTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.ScrollBarDisplayType));
		L.RegVar("Default", get_Default, null);
		L.RegVar("Visible", get_Visible, null);
		L.RegVar("Auto", get_Auto, null);
		L.RegVar("Hidden", get_Hidden, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.ScrollBarDisplayType>.Check = CheckType;
		StackTraits<FairyGUI.ScrollBarDisplayType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.ScrollBarDisplayType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.ScrollBarDisplayType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ScrollBarDisplayType.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Visible(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ScrollBarDisplayType.Visible);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Auto(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ScrollBarDisplayType.Auto);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hidden(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.ScrollBarDisplayType.Hidden);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.ScrollBarDisplayType o = (FairyGUI.ScrollBarDisplayType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

