//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_TouchScreenKeyboardTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.TouchScreenKeyboardType));
		L.RegVar("Default", get_Default, null);
		L.RegVar("ASCIICapable", get_ASCIICapable, null);
		L.RegVar("NumbersAndPunctuation", get_NumbersAndPunctuation, null);
		L.RegVar("URL", get_URL, null);
		L.RegVar("NumberPad", get_NumberPad, null);
		L.RegVar("PhonePad", get_PhonePad, null);
		L.RegVar("NamePhonePad", get_NamePhonePad, null);
		L.RegVar("EmailAddress", get_EmailAddress, null);
		L.RegVar("Social", get_Social, null);
		L.RegVar("Search", get_Search, null);
		L.RegVar("DecimalPad", get_DecimalPad, null);
		L.RegVar("OneTimeCode", get_OneTimeCode, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.TouchScreenKeyboardType>.Check = CheckType;
		StackTraits<UnityEngine.TouchScreenKeyboardType>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.TouchScreenKeyboardType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.TouchScreenKeyboardType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASCIICapable(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.ASCIICapable);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NumbersAndPunctuation(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.NumbersAndPunctuation);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_URL(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.URL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NumberPad(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.NumberPad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PhonePad(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.PhonePad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NamePhonePad(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.NamePhonePad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmailAddress(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.EmailAddress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Social(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.Social);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Search(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.Search);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DecimalPad(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.DecimalPad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneTimeCode(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TouchScreenKeyboardType.OneTimeCode);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.TouchScreenKeyboardType o = (UnityEngine.TouchScreenKeyboardType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

