---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/27 15:24
---

local EmojiUtil = {}
local EmojiMgr = EmojiMgr--C#脚本
local ItemTab = require("Tables.ItemConfig")


--All atlas
local mEmojiDic, mEmojiIsLoaded

--txt.emojies=EmojiUtil:Init--      mEmojiDic是Dictionary<uint, Emoji>类型.lua没有uint类型
function EmojiUtil:Init()
    if not mEmojiIsLoaded then
        loggZSXError("TTT")
        EmojiMgr.GetInstance():Init("Emoji", ".*")
        mEmojiDic = EmojiMgr.GetInstance():GetEmojiDic()
        mEmojiIsLoaded =true
    end
    return mEmojiDic
end


--获得图标
function EmojiUtil:GetEmoji(str)
    if not mEmojiIsLoaded then
        EmojiMgr.GetInstance():Init("Emoji", ".*")
        mEmojiDic = EmojiMgr.GetInstance():GetEmojiDic()
        mEmojiIsLoaded =true
    end
    return mEmojiIsLoaded:GetEmoji(str)
end

----以后统一用这种
local mItemEmojiNumberDics = {}
function EmojiUtil:GetItemEmojiNumber(itemId, itemNum)
    if not mItemEmojiNumberDics[itemId] then
        mItemEmojiNumberDics[itemId] = {}
        mItemEmojiNumberDics[itemId][itemNum] = self:GetEmoji(ItemTab[itemId].smallIcon) .. (itemNum)
    elseif not mItemEmojiNumberDics[itemId][itemNum] then
        mItemEmojiNumberDics[itemId][itemNum] = self:GetEmoji(ItemTab[itemId].smallIcon) .. (itemNum)
    end
    return mItemEmojiNumberDics[itemId][itemNum]
end

return EmojiUtil
